version: "3"

services:
  app:
    container_name: app
    build: .
    environment:
      - MONGO_URL=mongo
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    links:
      - mongo

  mongo:
    container_name: mongoDB
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"